name: Generate Tiles from Input

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Tile name'
        required: true
      style:
        description: 'Map style to be used for tile generation (self, mapbox, bing, planet, or esri)'
        default: 'bing'
        required: true
      bounds:
        description: 'Geographical bounds for the tile generation in "minLongitude,minLatitude,maxLongitude,maxLatitude" format'
        default: '-54.28772,3.11460,-54.03630,3.35025'
        required: true
      zoom_level:
        description: 'Zoom level for which the tiles will be generated'
        default: '15'
        required: true
      monthyear:
        description: 'Month and year for which the tiles are generated, in YYYY-MM format'
        required: false
      mapbox_style:
        description: 'Mapbox style in the format <yourusername>/<styleid>'
        required: false
      apiKeySecret:
        description: 'Api key secret name, defaults to API_KEY'
        required: false
      useSSH:
          description: 'If true, will will copy file to remote machine, else will upload as artifact.'
          default: 'true'
          required: false
      sshHost:
        description: 'Host of the remote mechine'
        default: 'cloud.earthdefenderstoolkit.com'
        required: false
      sshTarget:
        description: "Remote machine's folder where to copy file"
        default: '/mnt/volume_nyc1_01/data/content/partners/test/tiles'
        required: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tile Command
        id: generate-tile-command
        run: |
          TILE_NAME="${{ github.event.inputs.name }}"
          STYLE="${{ github.event.inputs.style }}"
          BOUNDS="${{ github.event.inputs.bounds }}"
          ZOOM_LEVEL="${{ github.event.inputs.zoom_level }}"
          MONTHYEAR="${{ github.event.inputs.monthyear }}"
          MAPBOX_STYLE="${{ github.event.inputs.mapbox_style }}"
          API_KEY_SECRET="${{ github.event.inputs.apiKeySecret }}"
          COMMAND="--style $STYLE -Z $ZOOM_LEVEL --bounds $BOUNDS -f $TILE_NAME"
          if [ -n "$API_KEY_SECRET" ]; then
            API_KEY=${!API_KEY_SECRET}
            COMMAND+=" --apikey $API_KEY"
          fi
          if [ -n "$MONTHYEAR" ]; then COMMAND+=" --monthyear $MONTHYEAR"; fi
          if [ -n "$MAPBOX_STYLE" ]; then COMMAND+=" --mapboxstyle $MAPBOX_STYLE"; fi
          if [ -n "$MINZOOM" ]; then COMMAND+=" --minzoom $MINZOOM"; fi
          if [ -n "$MAXZOOM" ]; then COMMAND+=" --maxzoom $MAXZOOM"; fi
          if [ -n "$TILE_FORMAT" ]; then COMMAND+=" --format $TILE_FORMAT"; fi
          if [ -n "$SCALE" ]; then COMMAND+=" --scale $SCALE"; fi
          if [ -n "$TILE_SIZE" ]; then COMMAND+=" --size $TILE_SIZE"; fi
          if [ -n "$ATTRIBUTION" ]; then COMMAND+=" --attribution $ATTRIBUTION"; fi
          if [ -n "$LOGO" ]; then COMMAND+=" --logo $LOGO"; fi
          if [ -n "$CENTER" ]; then COMMAND+=" --center $CENTER"; fi
          if [ -n "$PIXEL_RATIO" ]; then COMMAND+=" --pixel_ratio $PIXEL_RATIO"; fi
          if [ -n "$LANGUAGE" ]; then COMMAND+=" --language $LANGUAGE"; fi

          echo "COMMAND=$COMMAND" >> $GITHUB_ENV
      - name: Scrape tiles
        run: |
          docker run --rm -v ${{ github.workspace }}/outputs:/app/outputs communityfirst/mapgl-tile-renderer:main ${{ env.COMMAND }}
      - name: Copy mbtiles to EDT Cloud
        if: ${{ github.event.inputs.useSSH && github.event.inputs.useSSH != 'false' }}
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ github.event.inputs.sshHost }}
          username: "root"
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "outputs/${{ github.event.inputs.name }}.mbtiles"
          target: ${{ github.event.inputs.sshTarget }}
          strip_components: 3
          timeout: 60s
          command_timeout: 30m
      - name: Setting correct file permissions
        if: ${{ github.event.inputs.useSSH && github.event.inputs.useSSH != 'false' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ github.event.inputs.sshHost }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: chown -R 1000:1000 ${{ github.event.inputs.sshTarget }}
      - name: Upload mbtiles file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.name }}.mbtiles
          path: outputs/*.mbtiles
          if-no-files-found: error # 'warn' or 'ignore' are also available, 'error' will fail the step
          retention-days: 90
