name: Generate Tiles

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      sshInfo: ${{ steps.load-ssh.outputs.sshInfo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install json5
      - name: Load manifest
        id: load-manifest
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const JSON5 = require('json5');
            const manifestContent = fs.readFileSync('./manifest.json', 'utf8');
            const manifest = JSON5.parse(manifestContent);
            console.log('manifest', manifest);
            core.setOutput('tiles', manifest.tiles);
            core.setOutput('ssh', manifest.ssh);
      - name: Set matrix for tile jobs
        id: set-matrix
        run: echo "matrix=${{ toJSON(steps.load-manifest.outputs.tiles) }}" >> $GITHUB_OUTPUT
      - name: Load SSH info
        id: load-ssh
        run: echo "sshInfo=${{ toJSON(steps.load-manifest.outputs.ssh) }}" >> $GITHUB_OUTPUT
  build-and-deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scrape tiles
        run: |
          docker run --rm -v ${{ github.workspace }}/outputs:/app/outputs communityfirst/mapgl-tile-renderer:main \
          --style ${{ matrix.style }} \
          -Z ${{ matrix.zoom_level }} \
          --bounds ${{ matrix.bounds }} \
          --monthyear ${{ matrix.monthyear }} \
          -f ${{ matrix.name }}
      - name: Copy mbtiles to EDT Cloud
        if: ${{ fromJson(needs.prepare.outputs.sshInfo).host }}
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ fromJson(needs.prepare.outputs.sshInfo).host }}
          username: ${{ fromJson(needs.prepare.outputs.sshInfo).username }}
          port: ${{ fromJson(needs.prepare.outputs.sshInfo).port }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ github.workspace }}/outputs/${{ matrix.name }}.mbtiles"
          target: "${{ fromJson(needs.prepare.outputs.sshInfo).target }}/${{ matrix.style }}-${{ github.run_id }}"
          strip_components: 3
          timeout: 60s
          command_timeout: 30m
      - name: Setting correct file permissions
        if: ${{ fromJson(needs.prepare.outputs.sshInfo).host }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ fromJson(needs.prepare.outputs.sshInfo).host }}
          username: ${{ fromJson(needs.prepare.outputs.sshInfo).username }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ fromJson(needs.prepare.outputs.sshInfo).port }}
          script: chown -R 1000:1000 "${{ fromJson(needs.prepare.outputs.sshInfo).target }}/${{ matrix.style }}-${{ github.run_id }}"
      - name: Upload mbtiles file as artifact
        if: ${{ !fromJson(needs.prepare.outputs.sshInfo).host }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}.mbtiles
          path: outputs/*.mbtiles
          if-no-files-found: error # 'warn' or 'ignore' are also available, 'error' will fail the step
          retention-days: 90
