name: Generate Tiles

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Tile name'
        required: true
      style:
        description: 'Map style to be used for tile generation (self, mapbox, bing, planet, or esri)'
        default: 'bing'
        required: true
      bounds:
        description: 'Geographical bounds for the tile generation in "minLongitude,minLatitude,maxLongitude,maxLatitude" format'
        required: true
      zoom_level:
        description: 'Zoom level for which the tiles will be generated'
        required: true
      monthyear:
        description: 'Month and year for which the tiles are generated, in YYYY-MM format'
        required: false
      mapbox_style:
        description: 'Mapbox style in the format <yourusername>/<styleid>'
        required: false
      apiKeySecret:
        description: 'Api key secret name, defaults to API_KEY'
        required: false
      minzoom:
        description: 'Minimum zoom level for which the tiles will be generated'
        required: false
      maxzoom:
        description: 'Maximum zoom level for which the tiles will be generated'
        required: false
      tile_format:
        description: 'Format of the tiles to generate (e.g., "png", "jpg")'
        required: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install json5
      - name: Generate Tile Command
        id: generate-tile-command
        run: |
          TILE_NAME="${{ github.event.inputs.name }}"
          STYLE="${{ github.event.inputs.style }}"
          BOUNDS="${{ github.event.inputs.bounds }}"
          ZOOM_LEVEL="${{ github.event.inputs.zoom_level }}"
          MONTHYEAR="${{ github.event.inputs.monthyear }}"
          MAPBOX_STYLE="${{ github.event.inputs.mapbox_style }}"
          API_KEY_SECRET="${{ github.event.inputs.apiKeySecret }}"
          MINZOOM="${{ github.event.inputs.minzoom }}"
          MAXZOOM="${{ github.event.inputs.maxzoom }}"
          TILE_FORMAT="${{ github.event.inputs.tile_format }}"
          SCALE="${{ github.event.inputs.scale }}"
          TILE_SIZE="${{ github.event.inputs.tile_size }}"
          ATTRIBUTION="${{ github.event.inputs.attribution }}"
          LOGO="${{ github.event.inputs.logo }}"
          CENTER="${{ github.event.inputs.center }}"
          PIXEL_RATIO="${{ github.event.inputs.pixel_ratio }}"
          LANGUAGE="${{ github.event.inputs.language }}"

          COMMAND="--style $STYLE -Z $ZOOM_LEVEL --bounds $BOUNDS -f $TILE_NAME"
          if [ -n "$API_KEY_SECRET" ]; then
            API_KEY=${!API_KEY_SECRET}
            COMMAND+=" --apikey $API_KEY"
          fi
          if [ -n "$MONTHYEAR" ]; then COMMAND+=" --monthyear $MONTHYEAR"; fi
          if [ -n "$MAPBOX_STYLE" ]; then COMMAND+=" --mapboxstyle $MAPBOX_STYLE"; fi
          if [ -n "$MINZOOM" ]; then COMMAND+=" --minzoom $MINZOOM"; fi
          if [ -n "$MAXZOOM" ]; then COMMAND+=" --maxzoom $MAXZOOM"; fi
          if [ -n "$TILE_FORMAT" ]; then COMMAND+=" --format $TILE_FORMAT"; fi
          if [ -n "$SCALE" ]; then COMMAND+=" --scale $SCALE"; fi
          if [ -n "$TILE_SIZE" ]; then COMMAND+=" --size $TILE_SIZE"; fi
          if [ -n "$ATTRIBUTION" ]; then COMMAND+=" --attribution $ATTRIBUTION"; fi
          if [ -n "$LOGO" ]; then COMMAND+=" --logo $LOGO"; fi
          if [ -n "$CENTER" ]; then COMMAND+=" --center $CENTER"; fi
          if [ -n "$PIXEL_RATIO" ]; then COMMAND+=" --pixel_ratio $PIXEL_RATIO"; fi
          if [ -n "$LANGUAGE" ]; then COMMAND+=" --language $LANGUAGE"; fi

          echo "COMMAND=$COMMAND" >> $GITHUB_ENV
      - name: Scrape tiles
        run: |
          docker run --rm -v ${{ github.workspace }}/outputs:/app/outputs communityfirst/mapgl-tile-renderer:main ${{ env.COMMAND }}
      - name: Upload mbtiles file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.name }}.mbtiles
          path: outputs/*.mbtiles
          if-no-files-found: error # 'warn' or 'ignore' are also available, 'error' will fail the step
          retention-days: 90
